### ISSUE TITLE
Updates to `withHighlightConfig`

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4057]
## Bug with `withPWA`
When using `withPWA`, the next build (and dev) works with:
```
module.exports = withHighlightConfig(withPWA(nextConfig));
```
But not with:
```
module.exports = withPWA(withHighlightConfig(nextConfig));
```

I wonder if this is a bug with other similar import patterns as well.

## Returning a function
-  It’s valid to have a function as a next config so withSentryConfig returns a function and your wrapper expects it to be an object

**Comment by jay-khatri** [comment]
@Vadman97 do you remember what this point is about?
> It’s valid to have a function as a next config so withSentryConfig returns a function and your wrapper expects it to be an object

**Comment by jay-khatri** [comment]
discord convo: https://discord.com/channels/1026884757667188757/1090029472700432424/1101969972793725059

**Comment by deltaepsilon** [comment]
In my testing, the problem appears to be with `withPWA`.

If I put `withHighlightConfig` on the outside, it consumes `withPWA` just fine, resulting in the following `nextConfig`:
```
{
  generateBuildId: [Function: generateBuildId],
  experimental: { appDir: true },
  webpack: [Function: webpack],
  productionBrowserSourceMaps: undefined,
  rewrites: [AsyncFunction: newRewrites]
}
```

If I wrap `withPWA` on the outside, it returns the following:
```
{ webpack: [Function: webpack] }
```

Wrapping `withPWA` on the outside results in a 404, possibly because it doesn't know how to handle the promise that `withHighlightConfig` returns. You can see that `withPWA` assumes that `nextConfig` is an object:

https://github.com/shadowwalker/next-pwa/blob/1e6af5fa9f6a807930f451adb5ab5078d5cda451/index.js#LL17C4-L17C15

Support for `nextConfig` promises landed on [Next.js v12.1.0](https://github.com/vercel/next.js/releases/tag/v12.1.0) on [PR #33662](https://github.com/vercel/next.js/pull/33662)

Solution:

Wrap like so `withHighlight(withPWA(config))`and it should work ok.
