### ISSUE TITLE
Add onboarding state for logs

### ISSUE THREAD

**Issue by et** [highlight/highlight#4213]
When we haven't captured any logs from a project, we should onboard appropriately -- directing them to an SDK and offering them the option use to `curl` to inject a log easily.

**Comment by Vadman97** [comment]
Just wanted to add that it is important to differentiate frontend vs backend logs onboarding states, since the frontend logs onboarding happens automatically with the `H.init` frontend integration. If backend logs are not recorded, the prompt should point to the new backend setup docs to help with getting started. 

For storing the onboarding state granularly, perhaps a new `model.go` table would make sense that stores `project_id, integration_name` (with a unique constraint on `project_id, integration_name` and where `integration_name` is an enum ie. `frontend_logs`, `backend_errors` or `backend_logs)  for features that a user has integrated? we could backfill this with existing `backend_setup` data and with other queries looking for backend errors but set this accurately for new projects that integrate backend logs.

**Comment by jay-khatri** [comment]
@Vadman97 right now, the "isIntegrated" process is quite simple. See:

https://github.com/highlight/highlight/blob/e5e0ff93c933e2f02738d96f2fc4df586a40582d/backend/private-graph/graph/schema.resolvers.go#L4503
and
https://github.com/highlight/highlight/blob/e5e0ff93c933e2f02738d96f2fc4df586a40582d/backend/private-graph/graph/schema.resolvers.go#L4521

Can we just add `isBackendLogsIntegrated` method that queries clickhouse here? Imo, there are only three states we want to check (first session, first backend error, first backend log). 

cc @ccschmitz

**Comment by Vadman97** [comment]
just talked with @jay-khatri and agreed that we should add a new `model.Project` `backend_logs_integrated` flag and set that rather than `backend_integrated` via `MarkBackendSetup`. the `MarkBackendSetup` message can have a new parameter that determines which backend feature is setup (errors or logs). this is a simple way to do this for now, and we can make this more generic in the future.

@et , are you still planning to work on this this week? noticed you unassigned yourself.

**Comment by et** [comment]
@jay-khatri said that Chris was going to pick this one up.

**Comment by jay-khatri** [comment]
+1

@ccschmitz, I think this is a matter of setting a postgres flag when a backend log comes through. @Vadman97 mentioned y'all were pairing tomorrow, so he can give you a tour if needed as well.

**Comment by jay-khatri** [comment]
Yes, I agree!
