### ISSUE TITLE
The dropdown should be a multi-select, and show a count for each entry.

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4416]
we currently have a menu component which doesn't support multiselect; we may want to go ahead and add this new functionality to the ui component library. will let @ccschmitz share thoughts on this front.

**Comment by ccschmitz** [comment]
I think we have been trying to use `Menu` for all the places we show a list in a dropdown, but we want to create a new `Select` component that can be used for something like this rather than trying to use `Menu`, which should be reserved for menus that don't need to main state (e.g. a list of links, like the user dropdown in the top right).

Check out some of the Ariakit docs for more details on the building blocks we should probably use to create this:

* https://ariakit.org/components/select
* https://ariakit.org/components/menu
* https://ariakit.org/components/menu#should-i-use-menu-or-select

Part of the confusion around this may also be because we don't differentiate between menus vs selects in our Figma components and everything is just a "dropdown" in the mocks.

https://www.figma.com/file/pAHlb8IFmVSewPJcphbjIH/Component-Library?type=design&node-id=34%3A321&t=Usgy19SBLT6VKkuw-1

**Comment by ccschmitz** [comment]
Also note that Ariakit recently had a major release so the examples in the docs won't quite be accurate for the version we have installed in our app. If you have bandwidth, maybe we could look at upgrading Ariakit prior to tackling this.
