### ISSUE TITLE
Sending and Visualizing Traces

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4446]
Issue to track interest in being able to send and visualize traces in Highlight.io, i.e. the ability to send traces to the highlight backend via our SDKs (with auto-instrumentation available) and visualize them in a flame-graph like UI. And of course, this would  support viewing "Related Traces" on the sessions, errors, and log views.

Please react to show interest and comment w/ any thoughts/questions/suggestions.

**Comment by yacinehmito** [comment]
This is the one thing missing for us in order to make highlight.io the all-encompasing observability platform. We are currently using Honeycomb for application-level traces. Their UX is hard to beat, but:

1. They are not open source (which will become a requirement as we need an observability stack we can run in highly controlled environments).
2. They only do one thing, so we have to supplement it with Sentry and Datadog.

Highlight.io has the potential to replace all of those.
