### ISSUE TITLE
Expose position/time of rage clicks in the replay canvas

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#4458]
Right now, we have rage click alerts, but we don't render them in the new timeline bar. 

Please react to show interest and comment w/ any thoughts/questions/suggestions.

**Comment by Vadman97** [comment]
we should show rage clicks in the events timeline and could also show them on the replay canvas ala the comments

![Image](https://user-images.githubusercontent.com/1351531/226497879-d39504ee-443d-4389-90a0-397cc1cc5112.png)

here how the comments overlay looks: 

![Image](https://user-images.githubusercontent.com/1351531/226498116-8fe6f2d8-d147-4971-9a0d-1dacfb4866d3.png)

we write rage click events to the db, so we should have timing data already, though we do not store the positions yet

![Image](https://user-images.githubusercontent.com/1351531/226498032-2f0a42fb-715e-4eaf-94a2-6ce038b2e71a.png)

**Comment by betty-alagwu** [comment]
Thank you @Vadman97 . I spent some time studying the code. I have a good understanding of how the data flows now.

I would love to get your help on some few challenges if possible.

1. I was able to find the `rage_clicks` from the API. But it seems it's being processed somehow based on the click events in [this part of the code here](https://github.com/highlight/highlight/blob/main/frontend/src/pages/Player/PlayerHook/PlayerState.ts#L857). Can you please share with me what was your goal with this code ? And due to this code I noticed rage clicks passed to the state is always an empty array even when the API responded with rage clicks.

2. Can you please confirm to me how the rage clicks will be displayed in the events timeline ? Currently I think all the clicks in the range period just show are regular click events like this:

![Screenshot 2023-03-21 at 9 47 35 PM](https://user-images.githubusercontent.com/94234459/226737659-0b377b49-26d7-43da-b3b5-2bd9976a8001.png)

3. About your comment above `...on the replay canvas ala the comments`. Please could you share more information ? I have some confusion on how they will be shown on the canvas.

Thank you for your patience with me and your clarifications. Looking forward to your answers so I can continue. Thanks.

**Comment by mayberryzane** [comment]
Hi @betty-alagwu 
1. We have two arrays there: `allClickEvents` and `rage_clicks`. That code matches rage clicks to their closest event from `allClickEvents` so that we have additional data about the rage click. It's not intended for the resulting array to be empty, it would be good to figure out what cases this is happening for and what's going wrong.
2. Rage clicks should be displayed as a separate category with its own color in that view. Maybe a darker red than the current errors color?
3. If you click on the replayer canvas in commenting mode (e.g. press 'C' while watching a session and then click) it will add an icon where the canvas was clicked. We would like to do something similar to mark the location of the rage click. This could be a follow up to adding the timeline event for them.
Thanks for taking a look at this and let me know if you have any follow up questions!

**Comment by betty-alagwu** [comment]
Hi @mayberryzane thank you very much for your reply yesterday. I worked some more today and came back with some more questions to make sure I'm on the right track.

1. About the issue of `allClickEvents` being empty, I added a small fix [in this commit ](https://github.com/highlight/highlight/commit/b85a50d8f0ba822d92b5e7f7b91c7a85b4f0545e). It has something to do with checking the wrong array for the session intervals. Can you please take a moment to check the tiny change I made and see if it makes any sense at all ?

2. After fixing the issue of `rageClicks` in `PlayerState`, I made my way to the [`TimelineIndicatorBarGraph` component here](https://github.com/highlight/highlight/blob/main/frontend/src/pages/Player/Toolbar/TimelineIndicators/TimelineIndicatorsBarGraph/TimelineIndicatorsBarGraph.tsx#L258). It seems this is where all events are combined to be displayed on graph. My plan is to add rage clicks here into the combined array and then have it display in the graph. Do you think this is the right direction ?

Sorry this is taking long, but as I learn more I will contribute faster in future. Thank you very much for your patience.

**Comment by mayberryzane** [comment]
Hi @betty-alagwu, sorry for the delayed response here -
1. that change looks correct to me! looks like `sessionEvents` is only assigned to the `s.sessionIntervals` objects so it would be empty in just `sessionIntervals`
2. that looks like a good approach to me!

Thanks again for your help here!

**Comment by betty-alagwu** [comment]
Hello @mayberryzane, thank you very much for your patience. I've been able to display the `RageClicks` on the event time line. here's a short video of how it works


https://user-images.githubusercontent.com/94234459/228936526-fd8e8f71-6012-4c7a-a6ae-3a990a804194.mp4

<br />

[here is the changes i've made](https://github.com/highlight/highlight/commit/b98c9dfdb38a82763d0a7911a896302bf6edd738)


This is my progress so far and i would love for you to confirm if this was the expectation for this task and if it isn't, i'm very happy to make changes.
<br />

**Comment by mayberryzane** [comment]
Hi @betty-alagwu, this looks great, thanks for including a video! Feel free to create a PR and I'll review it. Thank you!

**Comment by betty-alagwu** [comment]
Ok thank you very much for your feedback, I'll create a PR right away
