### ISSUE TITLE
new setup page showing `object` for all sdk values

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#4590]
not sure how to repro this yet but seems to happen randomly

![image](https://user-images.githubusercontent.com/1351531/225129409-dddf2eab-b383-4f5d-af65-575faabdfc1c.png)

my session had strict privacy but here it is
https://app.highlight.io/1/sessions/WvFEZstQk6QcO2ePbNhwuwvA3W5g?ts=37.025600000381466

**Comment by jay-khatri** [comment]
Session to aid w/ debugging (seems like all those errors are what are problematic?): 
https://app.highlight.io/1/sessions/AariVmKISdom41oTSgSwY68zUq40?page=1&segment=%7B%22id%22%3A%2256%22%2C%22name%22%3A%22Actual%20Users%22%7D

**Comment by ccschmitz** [comment]
We chatted about this in Waterloo today. Believe the culprit is something with how a code string is broken about to build the markup for the DOM inside of react-syntax-highlighter. We even counted the number of `[object Object]`s being displayed and the number of DOM elements being rendered and it seemed to add up.

It also appears react-syntax-highlighter isn't being maintained anymore, so we may look around to see if there are other options.

**Comment by ccschmitz** [comment]
Hoping this is resolved by https://github.com/highlight/highlight/pull/4789, so I'm going to close this but will monitor.

I did look at other options for syntax highlighting, and although react-syntax-highlighter hasn't received any updates in a while, most of the popular syntax highlighting components hadn't been updated in a while, which might be because the underlying library they all seem to use ([prism](https://github.com/PrismJS/prism)) hasn't received any updates in quite a while.
