### ISSUE TITLE
Add a tab in the session viewer entitled "Backend Logs" where we query all the backend logs for a given session

### ISSUE THREAD

**Issue by et** [highlight/highlight#4786]
* should we always show this? Most folks won't have backend logs set up so should we conditionally show it? Would we want an empty state?
* The UX of Console Logs is different from the log viewer. Are we trying to match the UX of Console Logs for Backend Logs or are we just going to embed the log viewer?
* Console Logs shows logs in Time ascending order whereas the Log Viewer shows it in descending order. We need to be consistent. Showing timestamps helps here.

**Comment by jay-khatri** [comment]
Thanks for clarifying on the product end.

> should we always show this? Most folks won't have backend logs set up so should we conditionally show it? Would we want an empty state?

Yes, let's always show it. When someone clicks into the tab, the title should say "Couldn't find any backend logs for this session" w/ subtext "Have you sent backend logs to highlight yet? If there's something wrong, feel free to reach out to us!".
<img width="478" alt="image" src="https://user-images.githubusercontent.com/20292680/228946085-9ef631e8-54f4-4dfe-a01b-34b67611e67c.png">

> The UX of Console Logs is different from the log viewer. Are we trying to match the UX of Console Logs for Backend Logs or are we just going to embed the log viewer?

We want to match the UX of console logs here, the idea being that this UI is a sneak peak of all the functionality in the log viewer.

> Console Logs shows logs in Time ascending order whereas the Log Viewer shows it in descending order. We need to be consistent. Showing timestamps helps here.

I say we match the console logs functionality for this tab so that all the logs tab in the session viewer are consistent.

**Comment by julian-highlight** [comment]
@jay-khatri I like the idea of doing that! The only concern I have is that the tabs of console logs & backend logs might get confused, because of their similar appearance. Unsure if that's actually that crucial for now though. Dev tools generally will receive some more love soon anyways. I would also try to keep layouts similar for now, just because changing them in each tab adds a lot of cognitive load to people. 

CC @et

**Comment by julian-highlight** [comment]
Feel free to give feedback [here](https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=7056-360834&t=lJQepFu5xUH5GQbm-11)

**Comment by julian-highlight** [comment]
Updated designs [here](https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=4451-205639&t=kx6Jg2FgdihM8m9V-11). I've added the filter dropdowns underneath! @et

**Comment by et** [comment]
Mocks are great. Will close this out and can track changes in the parent ticket.
