### ISSUE TITLE
Revamp the error + session UI filters

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5038]
- [x] duplicate values
- [x] is / contains selection glitchy 
- [x] sort keys by relevance (filter out ones with very few values)
- [x] ui janky (e.g. 0 height loading state on switching from sessions to logs)
- [x] should be case insensitive everywhere (e.g. errors -> browser -> "chrome")

**Comment by mayberryzane** [comment]
loom about ui jankiness: https://www.loom.com/share/ea978682a3784000b01985c76ffa6e84

**Comment by ccschmitz** [comment]
Is this ticket mostly about fixing a few bugs or are we actually "revamping" the filters?

@julian-highlight and I discussed moving toward a text-based filter input for consistency across searching in different areas of the app. Not sure if that's something @jay-khatri's is bought in on or if it's relevant to this ticket, but wanted to flag it in case we're investing in the UI since it might be worth thinking about migrating to the same components we use in logs search.

**Comment by mayberryzane** [comment]
@ccschmitz this ticket is just about these specific bugs, there's another ticket I was working on #5040 to cut over to the new UI components
