### ISSUE TITLE
implement filter dropdown Errors/Sessions using figma design

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5040]
https://www.figma.com/file/pAHlb8IFmVSewPJcphbjIH/Component-Library?node-id=424-8811&t=roqpiRvZkabjR2kN-11

@julian-highlight is there a new style for dropdowns? any other design improvements we should make here?

**Comment by julian-highlight** [comment]
@Vadman97 
Here's the OG format for a dropdown: [Dropdown component](https://www.figma.com/file/pAHlb8IFmVSewPJcphbjIH/Component-Library?node-id=35-361&t=LqUepKR9SmnGYWpd-11)


I've created a specific filter designs a months ago here: [Error Filter Dropdown](https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?node-id=5020-222338&t=XzncfyAHg9YH64ww-11)

I could imagine (regarding scale) that we could use icons displaying the type of filter (single select, multi select, ...), instead of contextual ones (like presented in the design). 

I feel like this could be the first and easiest step we could do to improve filters on the left panels.
