### ISSUE TITLE
Add github as a more developer-friendly authentication flow

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5565]
we occasionally hear from customers that adding github authentication would be nice. e.g. 
<img width="569" alt="image" src="https://github.com/highlight/highlight/assets/20292680/620582e7-bd3e-412b-95f5-66f345ff6393">

(need to remember to reply to this tweet once this is done)

**Comment by SpennyNDaJets** [comment]
@julian-highlight saw this was blocked by design - I think all we need is an additional button on the sign in/sign out page, and we can let the popup do all the rest?

My very low effort button I created to focus on functionality
![Screenshot 2023-06-07 at 4 02 20 PM](https://github.com/highlight/highlight/assets/17744174/6e3ff6f6-ffca-4bc8-a90f-cdd29ee22ab1)

**Comment by julian-highlight** [comment]
Let me know when we add more options here. I've created a design a few months back that works also on a scale! 

For now this works perfectly! Thanks for taking this over 👍 
<img width="402" alt="image" src="https://github.com/highlight/highlight/assets/114743131/91b8f366-54d1-486a-ac50-1e08f80cc009">
