### ISSUE TITLE
Chrome extension errors are not being filtered out on the ingest side

### ISSUE THREAD

**Issue by et** [highlight/highlight#5604]
See [comment](https://github.com/highlight/highlight/pull/4794#pullrequestreview-1374067816).

**Comment by Vadman97** [comment]
we should filter out the entire error object rather than filtering the stacktrace for the error.

* setting should filter out chrome extension errors on the ingest, just like we do [with manual filters](https://github.com/highlight/highlight/blob/dc2d0ecbc731587ce2cbf47a5cc947cb7cfe7afd/backend/public-graph/graph/resolver.go#L2434-L2441) 
* we should switch the chrome extension filter setting to default-off
