### ISSUE TITLE
multiple notifications happen for instances of the same error group

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5613]
in #highlight-alerts, we're seeing a bunch of notifications for the same error group, one notification from each instance.
![image](https://github.com/highlight/highlight/assets/1351531/5c62d84a-781d-463e-b337-abcf4aed193a)
all pointing to https://app.highlight.io/1/errors/pWIfGyjrJ0bfykXIs1hGwyiYxC1N/instances/...

the error alert is configured to notify once per 30 minute window
https://app.highlight.io/1/alerts/433
![image](https://github.com/highlight/highlight/assets/1351531/26a30946-6961-4f3a-a4a4-aae900490920)

could we troubleshoot why the alerts for the same error group aren't getting throttled?

**Comment by SpennyNDaJets** [comment]
Think I've tracked this down to being due to still referencing the `AlertEvents` table here: https://github.com/highlight/highlight/blob/78b1cb6007a4545cbe213b90bb9fe11b649f7714/backend/public-graph/graph/resolver.go#L1631

This table was swapped out for the `ErrorAlertEvent`, `SessionAlertEvent`, and `LogAlertEvent` tables as part of [this PR](https://github.com/highlight/highlight/pull/5464/files).

Also noticed we reference this table as part of the [GetDailyFrequency](https://github.com/highlight/highlight/blob/78b1cb6007a4545cbe213b90bb9fe11b649f7714/backend/model/model.go#L1991), which is why the "No recent alerts" may not be working

![Screenshot 2023-06-22 at 10 51 26 AM](https://github.com/highlight/highlight/assets/17744174/32ec4de8-f3ed-4592-8d88-4e1ae10af436)

Next steps - I am going to work on migrating these queries to use the appropriate tables.
