### ISSUE TITLE
Images not loading in NextJS using `HighlightInit`

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#5677]
**Describe the bug**
> i'm writing to you because we have a bug when we put the HighlightInit as you recommends in the documentation in my layout.tsx (We are using the latest next js version).

**To Reproduce**
See notion doc [here](https://www.notion.so/runhighlight/guruhotel-image-issue-c46d268b2c544dd9930d1553db14e4cd?pvs=4)

**Comment by gurustiven** [comment]
If you want to reproduce just make a nextjs (13.4) project and put some of this images with the normal <img /> tag:

https://i.travelapi.com/lodging/11000000/10140000/10130300/10130300/c9095011_z.jpg
https://i.travelapi.com/lodging/11000000/10140000/10130300/10130300/de81d135_z.jpg

when we add the HighlightInit in our main Layout.tsx the images are blocked by CORS.

**Comment by deltaepsilon** [comment]
I was able to reproduce!

`H.init` is modifying the network request:

![image](https://github.com/highlight/highlight/assets/878947/0cd26fb0-10d6-4f49-8ba8-170a401e7287)

**Comment by deltaepsilon** [comment]
I found the issue. Set `<HighlightInit inlineImages={false} />` and it's resolved.

**Comment by deltaepsilon** [comment]
On further investigation, I see that `inlineImages` is only defaulted to `true` on localhost. Let me know if this issue continues to show up in production after explicitly setting `inlineImages={false}`.

**Comment by Vadman97** [comment]
Hey @gurustiven, wanted to follow up here and check in. If you have highlight sessions with the broken images, would you mind sharing a link here or over email? Thanks.

**Comment by gurustiven** [comment]
Hi Vadim, we had to remove highlight because not only were broken the images, also our search engine got some errors after enable it.

For the moment we have decided to remove.

Thanks for the following.

*Stiven Martínez
* Head Of Product & Co-Founder

*M:* (+57) 3117252993 ( tel:(+57)%203117252993 ) *LinkedIn ( https://www.linkedin.com/company/guruhotel/ ) Instagram ( https://www.instagram.com/guruhotelcom/ ) Twitter ( https://twitter.com/GuruHotelHQ ) Facebook ( https://www.facebook.com/guruhotelmx/ ) Facebook ( ***@***.*** )* www.guruhotel.com ( https://www.guruhotel.com/ )
