### ISSUE TITLE
Look into performance problems when toggling live mode in replayer

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#5713]
There is some jank when toggling live mode in the replayer. We believe there are two separate issues:

1. When you load a live session it can take a long time because the data isn't chunked (because it hasn't been processed yet) and we have to load all the data before can play anything.
2. When transitioning in and out of live mode all the data being loaded into rrweb blocks JS execution of our app and causes some things to freeze on the screen momentarily.

Here's a profile of from toggling live mode on and off. Note that this is a local profile so you see some things called twice because of strict mode. We believe the call to rrweb's `applyEventsSynchronously` is what is blocking JS execution.

![Image](https://github.com/highlight/highlight/assets/308182/65c8210a-3a96-4b82-9b97-20db31076150)

**Comment by Vadman97** [comment]
Thanks @ccschmitz ! I think the issue can be tackled in two parts:
1. addressing the slow rrweb `applyEventsSynchronously` calls by making sure live mode only loads the **last** full snapshot, rather than all events. for a 'show live' session, that's easy to implement, but for regular live sessions loaded in their entirety, we would need to incrementally store chunk data as a session is recorded to load only one chunk at a time.
2. addressing slow `GetSessionPayload` graphql calls. iirc, that endpoint can be slow querying events from redis. this might not be a problem after #1 is addressed (only sending one chunk of events data at a time).

**Comment by Vadman97** [comment]
@mayberryzane , would it be possible to store `event_chunk` rows in postgres for each incremental snapshot as we receive `PushPayload` events, or do we have do create chunks in one sweep when we process the session?
