### ISSUE TITLE
setup page for hobby deploys should insert `backendUrl` setting into the sdks

### ISSUE THREAD

**Issue by Vadman97** [highlight/highlight#5742]
https://www.highlight.io/docs/getting-started/self-host/self-hosted-hobby-guide
rather than telling folks to populate the `backendUrl` for self-hosted stacks, 
we can just update the setup page of a self-hosted instance (by detecting that the `REACT_APP_PUBLIC_GRAPH_URI` is set to a non-default value) to provide that option automatically in the SDK code snippets.

**Comment by ccschmitz** [comment]
@Vadman97 do we want to update all the places we show an example with `H.init` in the setup docs to include `backendUrl`?

**Comment by KaranJagtiani** [comment]
I was about to create a new issue for this since I faced it while setting up Highlight on my local machine. Good to know that its already known and we want it to be fixed.

I agree that populating the `backendUrl` attribute in the "Initialize the client SDK." section if the host is not `app.highlight.io` will make it easier and faster to get started for those setting Highlight up on their own infrastructure or local machine.

I am aware of how to resolve this issue. Can I work on this? @jay-khatri

**Comment by jay-khatri** [comment]
Sounds good @KaranJagtiani!

**Comment by jay-khatri** [comment]
If I'm not mistaken, this would mean updating the content in [QuickstartContent](https://sourcegraph.com/github.com/highlight/highlight/-/tree/highlight.io/components/QuickstartContent) to include a backendURL flag in each of our SDKs. Making changes to these files should automatically make respective changes on the setup pages in our main app (e.g. see the import [here](https://sourcegraph.com/github.com/highlight/highlight/-/blob/frontend/src/pages/Setup/SetupDocs.tsx?L14)). 

cc @ccschmitz and @Vadman97.
