### ISSUE TITLE
Links in project documentation should open in a new browser tab

### ISSUE THREAD

**Issue by TheJazzDev** [highlight/highlight#5797]
**Describe the bug**
When developers/users are navigating the documentation, when clicking on links to external  resources, these links should open in a new browser tab instead of the documentation tab. This will enable one to keep things organise and not back and fourth trying to stay in the documentation tab.

**To Reproduce**

1. Go to https://www.highlight.io/docs/getting-started/overview
2. Click any external link

**Expected behavior**
All external links should be opened in a new tab

**Comment by jay-khatri** [comment]
Hey @TheJazzDev thanks for the report. This makes sense. We could also add an icon that represents an external link, like so:
<img width="649" alt="image" src="https://github.com/highlight/highlight/assets/20292680/64f86f0e-c690-4c25-ac68-c5aa022c48ef">

If you're interested in working on this, let us know. Otherwise, appreciate the report!

**Comment by TheJazzDev** [comment]
Hi Jay,

I'm interested in working on this, would appreciate if this issue can be
assigned to me so i can start working on it.

Thanks.

**Comment by TheJazzDev** [comment]
Hi Jay,

I'm interested in working on this, would appreciate if this issue can be
assigned to me so i can start working on it.

Thanks.

**Comment by Vadman97** [comment]
Thanks @TheJazzDev ! Code for docs is in this repo at https://github.com/highlight/highlight/tree/main/highlight.io
To run the docs next.js app, run `yarn; yarn dev:highlight.io`

**Comment by TheJazzDev** [comment]
I'm on it.
