### ISSUE TITLE
Highlight.io Documentation website sometimes doesn't responds

### ISSUE THREAD

**Issue by TheJazzDev** [highlight/highlight#5799]
**Describe the bug**
Over the past 3 days I've been trying to access the highlight.io documentation page so that i can set up the project locally but the website hasn't been responding the way it should. Sometimes it opens and but i won't be able to go past the overview page and sometimes it doesn't open at all. The website performance is also poor especially on mobile.

**To Reproduce**
Try to access the documentation page to see if it opens or not.

**Expected behavior**
Page should open without issues at all.

**Screenshots**
I made a 3 minutes screen record to show exactly the issue i'm facing.

[Screencast from 30-06-2023 22:27:42.webm](https://github.com/highlight/highlight/assets/95573407/1bfb4617-5938-4527-a8cb-c107f800fbd9)

Performance screenshot on PC
![image](https://github.com/highlight/highlight/assets/95573407/b9e3db08-cfdb-4221-ac2d-0cd8977f8b4d)

Performance screenshot on Mobile
![image](https://github.com/highlight/highlight/assets/95573407/01162b50-8921-4d40-9226-b660c2dc17c8)

Internet Speed Test
![image](https://github.com/highlight/highlight/assets/95573407/ace4076b-bc70-4e0f-bdf6-c9f6520aca53)

**Comment by Vadman97** [comment]
My guess is this has to do with your slow network bandwidth (2 mbps download is quite slow, and I can reproduce the issue you are having by enabling slow 3g network throttling in google chrome). our next.js docs load quite a lot of data for ISR which might block the initial render. there might be something we can do about it though, because our doc pages have quite a bit of data that is duplicated (things that could be pulled out into a separate ISR component to avoid the redundant downloads).
![image](https://github.com/highlight/highlight/assets/1351531/f80213af-506a-4334-b0ea-604598ef5068)
![image](https://github.com/highlight/highlight/assets/1351531/37dee941-e21e-43d3-8ade-bcff01f8a741)

**Comment by Vadman97** [comment]
@TheJazzDev can you check if you have better performance when loading the docs locally (from `yarn dev:highlight.io`)?

**Comment by TheJazzDev** [comment]
@Vadman97 I agree it may be slow bandwidth as you have said but if you replicate it with slow 3g throttling in google chrome, it will take time to download all necessary file but shouldn't have show error. If you go to the landing page and you you click on the docs link, it doesn't immediately load that page, i don't know if you noticed that also. 

Anyways, I'm already setting up locally and i will check this issue. Also, we should definitely be loading some of the pages dynamically. No need downloading all the files at once when the user may probably not use all. So loading them dynamically only when needed is a viable option if i may say. I can also work on optimising this issue if assign to me. That way we can have a better performance. Thanks.

**Comment by jay-khatri** [comment]
@TheJazzDev feel free to ticket/assign yourself to that.
