### ISSUE TITLE
Use new tooltips on histogram for "last 30 days" + error result cards

### ISSUE THREAD

**Issue by ccschmitz** [highlight/highlight#6020]
examples:
<img width="365" alt="image" src="https://github.com/highlight/highlight/assets/20292680/b128683c-4771-494b-a539-1e6d701dcf4e">
<img width="367" alt="image" src="https://github.com/highlight/highlight/assets/20292680/cd71649a-95d3-47e1-9457-441e4cc46826">

```[tasklist]
### Tasks
- [ ] https://github.com/highlight/highlight/issues/6119
- [ ] Update Histogram to use new tooltip
```

**Comment by SpennyNDaJets** [comment]
Looks like this will have to touch two common components:
1) BarChart - Highlight's custom bar chart build with HTML components
  a) Used on the Error result cards and details
  b) Straightforward swap from Antd tooltip to UI tooltip
2) Histogram - Recharts' bar chart that abstracts out a lot of logic
  a) Used on the Error pae's histogram
  b) From spike seems we may want to swap out the usage of the histogram for Highlight's BarChart

**Comment by SpennyNDaJets** [comment]
@ccschmitz @julian-highlight is an acceptable solution here to update the Histogram's custom tooltip we pass to match the new designs, or do we want to use the new UI tooltip component? (See https://github.com/highlight/highlight/issues/6020#issuecomment-1652157436 for more context)

**Comment by julian-highlight** [comment]
I mean ideally we use the same component for any tooltip. Short term we could hack the old ones to match the styles! We might run into issues again though, if we want to change styles/themes. @SpennyNDaJets

**Comment by SpennyNDaJets** [comment]
@julian-highlight makes sense. I'll dig a little deeper into the complexity to use our new Tooltip component with Recharts, but otherwise seems like the options are:
1. Migrate the charts slowly off Recharts (bigger upfront feat to build some of the functionality into our bar chart)
2. Update the styles of the Rechart custom tooltip

1 may make more sense if we are looking to migrate off of Recharts to begin with, so will take to some folks
