### ISSUE TITLE
Named export 'BatchSpanProcessor' not found. The requested module '@opentelemetry/sdk-trace-base' is a CommonJS module

### ISSUE THREAD

**Issue by mattiaz9** [highlight/highlight#6093]
**Describe the bug**
I'm following the Next configuration here: https://www.highlight.io/docs/getting-started/fullstack-frameworks/next-js
but I can't make it work using a `.mjs` configuration.

When I start the project I get the error: `SyntaxError: Named export 'BatchSpanProcessor' not found. The requested module '@opentelemetry/sdk-trace-base' is a CommonJS module, which may not support all module.exports as named exports.`

**To Reproduce**
Follow the Next configuration guide using Next 13 app dir and a `.mjs` next config file.

**Additional context**
- I'm using next 13 app router, and `next.config.mjs` config file.
- With a `.js` next config file it works fine.
- I already tried setting `type: "module"` in the `package.json`

**Comment by deltaepsilon** [comment]
@mattiaz9 We use a `next.config.mjs` file in our test Next.js project:

https://github.com/highlight/highlight/blob/main/e2e/nextjs/next.config.mjs

Adjusting your `type: "module"` won't help. You've run into the classic CJS vs ESM misery as described here:

https://adamcoster.com/blog/commonjs-and-esm-importexport-compatibility-examples

My suggestion is to try to NOT use `withHighlightConfig`. It helps with private source maps and some proxying (https://www.highlight.io/docs/sdk/nextjs#configureHighlightProxy), but most apps don't need either.

I'm going out of town until Monday with limited connectivity, but let me know how it goes. You could also respond with a copy of your `next.config.mjs` file that I could try debugging.

**Comment by mattiaz9** [comment]
@deltaepsilon removing `withHighlightConfig` makes it start, but then at the first page request it crashes with the same error:
```bash
  BatchSpanProcessor
  ^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'BatchSpanProcessor' not found. The requested module '@opentelemetry/sdk-trace-base' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@opentelemetry/sdk-trace-base';

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

**Comment by deltaepsilon** [comment]
@mattiaz9 I'm working on a potential fix.

I suspect that changing up the import in your `node_modules/@highlight-run/node/dist/index.mjs` file could help.

Try editing the file directly in `node_modules`. Instead of the the original `BatchSpanProcessor` import, try something like this:

```javascript
// src/client.ts
import otelSdkTraceBase from "@opentelemetry/sdk-trace-base";
var { BatchSpanProcessor } = otelSdkTraceBase;
```

I'm testing it myself to see if I can push this change and bump our `@highlight-run/node` version. I don't know if it fixes your problem.

**Comment by Vadman97** [comment]
https://www.npmjs.com/package/@highlight-run/next/v/3.1.5 and https://www.npmjs.com/package/@highlight-run/node/v/3.1.5 are published with a fix for this. The bug came back to a bad export in `@opentelemetry` packages we depended on. See [Discord](https://discord.com/channels/1026884757667188757/1132761273432539278) for more context.
