### ISSUE TITLE
Grab cursor is unclear

### ISSUE THREAD

**Issue by jay-khatri** [highlight/highlight#6223]
see second part of this gif:
![CleanShot 2023-08-03 at 11 40 25 (2)](https://github.com/highlight/highlight/assets/20292680/87204bcd-34a9-4298-93f6-68f161b3c18f)

"The "grab" cursor on the bar above dev tools makes me think I can use that to resize the bottom area, but evidently you have to click the middle of it. Ideally you could click anywhere on the bar to resize, or at least disable "cursor: grab" elsewhere."

**Comment by ccschmitz** [comment]
I think the problem here is that the resize bar underneath the timeline is draggable, but it's not technically draggable until you zoom in.

https://www.loom.com/share/4dd85ecf438e4e77b3f3f0bb51ffbb15

@jay-khatri @julian-highlight what do you think about changing the cursor on the resize bar to the default unless you are zoomed in?

**Comment by julian-highlight** [comment]
Could we use the double arrow instead? Generally we could bring the in prod state of the resize thingy closer to the designs to improve UX as well! 🤔 @ccschmitz 
![image](https://github.com/highlight/highlight/assets/114743131/2db78311-3721-4c2a-a628-11e253fdb2ca)

**Comment by ccschmitz** [comment]
@julian-highlight yeah, I think we can use the [`ew-resize` cursor value](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor) here!
