### ISSUE TITLE
Make the OTLP-Endpoint configurable

### ISSUE THREAD

**Issue by lksmrqrdt** [highlight/highlight#6538]
**Is your feature request related to a problem? Please describe.**
The backend of Highlight hardcoded the Open Telemetry Endpoint to a specific location, depending on the environment either `http://collector:4318` or `http://localhost:4318`. This is suboptimal, as I'm currently working on a Helm Chart for Highlight, which shouldn't rely on static hostnames.

The exact location of the issue lies here: https://github.com/highlight/highlight/blob/2ab537cbf0ae7b10215fd9b4cd26bd0dc154e0d6/backend/main.go#L237

**Describe the solution you'd like**
I would love to have an env-variable, e.g. `OTLP_ENDPOINT`, which would allow me to set up a custom endpoint, which is not `http://collector:4318` or `http://localhost:4318`.

**Describe alternatives you've considered**
For the time being, I can deviate from the usual helm template, and just adjust the service endpoint.

**Additional context**
-

**Comment by Vadman97** [comment]
I think this makes sense since in the context of a helm deploy, the otlp ingest endpoint would be the collector container which would have a dynamic hostname (not the same node as the backend). Should be straightforward to add this in hobby deploy, and we can always fallback to `http://localhost:4318`  

https://github.com/highlight/highlight/blob/0dd7657bc22d56166090202f864eb9084e076233/docker/compose.hobby.yml#L18-L58

https://github.com/highlight/highlight/blob/0dd7657bc22d56166090202f864eb9084e076233/docker/.env
