### ISSUE TITLE
Cross-origin images don't load when highlight.io is enabled

### ISSUE THREAD

**Issue by kevlened** [highlight/highlight#7267]
**Describe the bug**
Without highlight.io, the cross-origin image renders.
With highlight, I receive CORS issues.

**To Reproduce**

1. Configure a vanilla remix example using `npx create-remix@latest`
2. Add an image on a different domain
3. Add highlight with your project id
4. `npm run dev`

**Expected behavior**
Image renders

**Screenshots**
Without highlight.io
![Screenshot 2023-12-03 at 15 47 49](https://github.com/kevlened/remix-vanilla/assets/955312/84adfea6-8f0f-45c0-989c-37f7d67ff34c)

With highlight.io
![Screenshot 2023-12-03 at 15 47 32](https://github.com/kevlened/remix-vanilla/assets/955312/40167367-a1c8-4889-9e9a-e12c6e4acd99)

**Additional context**
[Here's an example you can clone](https://github.com/kevlened/remix-vanilla/pull/1)

**Comment by Vadman97** [comment]
Hey @kevlened , thanks for the example, allowed me to repro much faster. In this case, this is caused by the image [inlining feature](https://www.highlight.io/docs/getting-started/fullstack-frameworks/next-js/advanced-config#configure-inlineimages) (which is enabled by default on localhost as often assets are served from localhost and won't be available at replay time). You'll want to turn off that feature to make sure images are not inlined on localhost to prevent cors issues (the cors error happens because we try to access the image in javascript, which requires CORS headers). 
![Screenshot from 2023-12-12 13-27-00](https://github.com/highlight/highlight/assets/1351531/8b10de7f-2c74-45cb-b035-e4367adf237b)
